Crop Yield Prediction/crop_yield_app/templates/index.html
index.html
main.html
organic.html

UI/UX and Accessibility Enhancements
Changes Made:
- **Performance**:
- Added lazy loading for carousel images
- Optimized image loading with Intersection Observer
- Improved responsive image handling
- **Accessibility**:
- Added ARIA labels and proper alt text
- Enhanced keyboard navigation
- Improved focus states for better tab navigation
- **UI Improvements**:
- Enhanced responsive design for all screen sizes
- Added smooth transitions and hover effects
- Improved button and interactive elements
- **Code Quality**:
- Organized and cleaned up CSS
- Improved JavaScript performance
- Better code structure and comments

Enhance UI and accessibility of index.html

---

about.css
about.html
index.html

Description:
This PR adds a new "About Us" page to the website ( Issue no. #80) 
Key updates include:
Created a new about.html page (or component/file depending on your tech stack).
Added routing/navigation link to the About Us page in the navbar.
Included content describing the purpose, mission.
Checklist:
Page created and styled
Linked in navbar
Tested across devices

Add About Us Page

---

firebase.js
index.html
login.css
login.html

**Add Google Sign-In to Login Form using Firebase Authentication**  
- **Name:** Chaitanya
- **GitHub ID:** ChaitanyaBadukale777
- **Email ID (for communication):** chaitanyabadukale757@gmail.com
- **Participation Program (if any):** GSSOC'25
**What have you added or modified in this pull request?**  
- Integrated Google Sign-In using Firebase Authentication SDK.
- Updated the login UI to include a “Sign in with Google” button using external CSS (login.css).
- Implemented authentication flow to handle Google login and session persistence.
- Added error handling for failed or canceled sign-in attempts.
- Enhanced overall user experience by enabling quick, one-click access for users with Google accounts.
Screenshot showing successful Google Sign-In integration in Firebase Authentication …

Add Google Sign-In to Login Form using Firebase Authentication

---

feed-back.css
feed-back.html
feed-back.js
main.css
main.html

This pull request adds a dedicated feedback page to the website. The changes include:
- Created three new files:
- feedback.html – Contains the feedback form structure
- feedback.css – Styles for the feedback form and page layout
- feedback.js – Handles basic form validation and submission logic
- Updated the navigation in main.html to include a link to the feedback page
- Modified main.css to support any necessary styling for the new link or layout adjustments
This feature helps users easily send feedback or support requests, improving overall user experience and engagement.

Added feedback page with HTML, CSS, JS and updated main pages

---

CODE_OF_CONDUCT.md

**📌 Purpose**
This PR adds a formal CODE_OF_CONDUCT file to the repository to establish community guidelines under GSSoC’25 and updates the Notice.js file to reflect the project’s participation and conduct expectations.
**🔗 Related Issue**
Fixed #89 
**🔧 Type of Change**
- [  ] Bug fix (non-breaking change)
- [  ] New feature
- [  ] Breaking change
**✅ How Has This Been Tested?**
- The CODE_OF_CONDUCT.md file was reviewed for formatting and content accuracy.
- Notice.js was updated and verified through local development environment.
- Environment Details:
1. OS: Windows 10
2. Editor: VS Code
3. Browser: Chrome 139
**📸 Screenshots** 
**📊 Impact / Performance**
- No impact on application performance.
- No new dependencies added.
**✅ Checklist**

Add CODE_OF_CONDUCT for GSSoC'25 contribution

---

Crop_Prices_Tracker/app.py
Crop_Prices_Tracker/static/styles.css
Crop_Prices_Tracker/templates/crop_price_tracker.html
main.html

New Feature Update:
Feature that allows farmers, agri-entrepreneurs, and stakeholders to view real-time crop prices from the Government of India's public API (data.gov.in). It fetches live data on various crops, including names, markets, locations, prices, and units, helping users stay updated with market trends and make informed selling decisions.

Crop Prices Tracker

---

Labour_Alerts/static/style.css
Labour_Alerts/templates/labour.html
farmer.css
farmer.html

Validate the labour form successfully.

Labour form validation

---

.gitignore.txt
app.py
script.js
smart_loan.html
style.css

This PR integrates Google's Gemini AI API into the AgriTech project's backend to dynamically assess loan eligibility for farmers based on form inputs.
- Issue #8 
- **Backend (`app.py`)**
- Added Flask route `/process-loan` to receive form submissions.
- Integrated Gemini 2.5 Flash model via `google.generativeai` for eligibility analysis.
- Sends structured prompt to Gemini API with the submitted JSON data.
- Returns markdown-formatted AI response to the frontend.
- **Frontend (`script.js`)**
- Dynamically renders forms based on selected loan type (Crop, Equipment, Water, Land).
- On form submission, sends collected data as JSON to the Flask backend.
- Renders Gemini's markdown response (loan eligibility result) in HTML format.
- Added print functionality for viewing a printable report.
- …

Integrated Gemini API for Smart Loan Eligibility Evaluation

---

index.html
style.css

Description: This PR resolves the issue where the scroll-to-top arrow was visible on the About Us page but missing on the Home page. The component has been refactored to ensure consistent rendering across all pages.
Changes Made:
Moved the scroll-to-top arrow into a shared layout component.
Verified conditional rendering based on scroll position.
Ensured responsiveness and accessibility remain intact.

Fix scroll-to-top arrow visibility on Home page

---

main.css
main.html
main.js

now fix when i scroll up and down the scroll down smoothly

nav bar issue n0 149 nav bar and footer are collide now both are fix

---

Crop_Planning/templates/cropplan.html
about.html
chat.html
cropCalendar.html
disease.html
farmer.html
index.html
main.html
organic.html
shopkeeper.html
smart_loan.html

This PR updates the **footer section across all pages of the AgriTech website** to make it more modern, user-friendly, and consistent with the site’s branding.  
- Redesigned footer layout with a clean and professional look  
- Added quick navigation links.
- Integrated social media icons with external links  
- Improved responsiveness for mobile and tablet devices  
- Ensured accessibility compliance.  
- Provides a consistent footer experience across all pages  
- Enhances navigation and accessibility for users  
- Builds trust by displaying contact details and social media links  
- Strengthens brand identity and design consistency  
Please review this PR and merge it.

Footer Section Update for All Pages  

---

login.css
register.css

Fixes #189 
Relates #189 
Closes #189 - Fixed password toggle eye placement
**Problem**: Incorrect Password toggle eye placement.
**Impact**: Fixed password toggle eye placement.
- ✅ Security test suite created (`test_security.py`)
- ✅ Client-side exposure eliminated
- ✅ Server-side configuration implemented
- ✅ Firebase security rules created
- ✅ Environment variables properly configured
---

Fixed password toggle eye placement

---

firebase.js
forgot-password.html

Closes #142 - Firebase security vulnerability with exposed API keys
**Problem**: Firebase API keys and sensitive configuration were exposed in client-side JavaScript code, allowing unauthorized database access.
**Impact**: This vulnerability exposed the entire Firebase project to potential unauthorized access and data breaches.
- **File**: `firebase.js`
- **Changes**: 
- Removed hardcoded Firebase configuration object
- Implemented secure async initialization that fetches config from server
- Added proper error handling and validation
- **Security Impact**: API keys no longer visible in browser developer tools
- **File**: `app.py`
- **Changes**:
- Added `/api/firebase-config` endpoint for secure config delivery
- Integrated environment variable loading with `python-dotenv`
- Updated …

Reset password funtionality

---

login.css
login.html
login.js
register.css

Fixed icon misalignment issues on the login page.
Added logo and additional information to the login page.
Updated design to ensure consistency between the login and register pages.

Fixed design issues on login and register pages for consistency

---

.github/pull_request_template.md

Added a pull request template
Closes #205

Create pull request template for contributors

---

feed-back.css
feed-back.html

- Closes #210 
The old one doesnt support dark theme and looks a bit messy
Updated the html file for better design with custom css
yes 
yes

Feedback form Redesign

---

main.css

- Closes #220 
Replaces the previous footer CSS with a new, visually rich and responsive design. Adds background patterns, decorative wave, improved grid layout, brand/logo styling, animated social media buttons, and refined copyright section. Updates media queries for better mobile and tablet support.
yes
yes
Screenshots:

Revamp footer styles with enhanced design and layout

---

shopkeeper.css
shopkeeper.html
shopkeeper.js

1. Search & Filter Enhancements
- Advanced search bar with search icon + clear button.
- Category filtering (Pesticide, Tractor, Harvester, Equipment).
- Location filtering by district/city.
- Sorting options (alphabetical, reverse, by location).
- Real-time results counter + reset filters.
2. Improved Card Design
- Better spacing, typography, and visual hierarchy.
- Icons for phone, location, and services.
- Clickable tel: links for phone numbers.
- Dual action buttons (Call / Directions + Details).
- Hover animations and visual feedback.
3. Responsive Grid Layout
- 3-column layout on desktop, 2 on tablet, 1 on mobile.
- Improved padding, spacing, and shadows.
- Mobile-optimized filter/search controls.
4. Interactive Features
- Dealer details modal with full profile & hours.
- Smooth …

Advanced Search, Filters & Responsive Dealer Listing UI

---

cropCalendar.css

- Closes #208 
the buttons of dark mode and the back button
fixed position for buttons 
yes 
minor changes
Before :

Fixed the overlaping buttons on the calender page

---

feed-back.css
feed-back.html
index.html
main.css
main.html

Issue no. #204
- Closes #.
- 
1.Updated Feedback page
2.Solved the problem : Thank you section was not visible but now its visible when i submit feedback.
3. Updated Footer of Dashboard page (main.html)
4.Solved login issue now when user click on dashboard he first have to login then he will redirect to dashboard page.

Updated ui of feedback form , footer of dashboard and solved login issue

---

main.css

Edited the hover effect of nav bar in main page. It promotes user enhancement and better UI.
Issue #230 is solved.

Edited hover effect

---

Crop_Planning/templates/cropplan.html

- Closes #242 
Changed all references to the logo image  for consistency and to reflect the correct asset location.
Yes
Yes
Before:

Update logo i cropplan.html

---

main.css
main.html

Introduces CSS variables and dark mode styles for main UI components, including loan guide sections, loan cards, and language select. Updates main.html to use CSS variables for colors and backgrounds, refines transitions, and enhances visual consistency for both light and dark themes.
- Closes #209 
Introduces CSS variables and dark mode styles for main UI components, including loan guide sections, loan cards, and language select. Updates main.html to use CSS variables for colors and backgrounds, refines transitions, and enhances visual consistency for both light and dark themes.
Yes
Yes
Before:
After:

Add dark mode support and improve UI styling

---

about.css
about.html

**Enhancement: Revamped About Us Page (SEO, Accessibility, UI/UX, Styling) (#269)**
---
This PR by **@keshripritesh** improves the **About Us page** by addressing SEO, accessibility, UI/UX, and styling enhancements.
The goal is to provide a **modern, responsive, and user-friendly design** while improving maintainability.
---
* Added descriptive `<meta>` tags (keywords, description, OpenGraph).
* Fixed duplicate favicon entries.
* Corrected heading structure for better search engine readability.
* Added descriptive `alt` text for images.
* ARIA labels for theme toggle & social icons.
* Improved contrast for light/dark themes.
* Added **scroll-to-top button** with smooth scrolling.
* Hover & transition effects on services and footer links.
* Section fade-in animations using Intersection …

Pull Request : UI/UX Enhancement: About Us Page

---

main.css

Modified the hover effects for grid item contents cards. Previously the contents used to disappear on hovering, now its working perfectly fine.
Issue #238 is resolved.

Modified hover effects

---

plantation.css

fixed  planatation navbar text visibility

---

index.html
main.html
style.css

Hii I added search bar issue #254
here is the screenshot

Added search bar

---

cropCalendar.css
cropCalendar.html

**Enhancement: Interactive Crop Calendar with Dark/Light Mode Support (#311)**
---
Fixes #311 
* ✅ Corrected **JavaScript linkage** → now properly uses `cropCalendar.js`.
* ✅ Added **Dark/Light mode toggle** with smooth transitions + sun/moon icons.
* ✅ Styled **Back button** and aligned it with theme toggle in header.
* ✅ Improved **Crop Selector** with modern styling (padding, borders, rounded corners).
* ✅ Updated **Calendar Display** with card-like UI, hover effects, and tooltips.
* ✅ Enhanced **Responsiveness** → works seamlessly on desktop, tablet, and mobile.
* ✅ Introduced **CSS variables** for colors → easier theme management.
---
* `cropCalendar.html`
* `cropCalendar.css`
---
* Wrong JS linkage (features not loading).
* Broken/misaligned header.
* Theme toggle inactive.
* Plain …

Pull Request : Interactive Crop Calendar Enhancement

---

Crop Recommendation/templates/index.html

- Closes #315 
Complete overhaul of the Agritech Crop Recommender page with modern design principles, improved user experience, and enhanced functionality. This redesign transforms the original form into a professional, accessible, and user-friendly interface.
- **Modern Design System**: Clean, professional interface with consistent spacing and typography
- **Dark/Light Mode**: Fully functional theme switching with smooth transitions
- **Enhanced Form UX**: Improved validation, auto-save, and visual feedback
- **Responsive Design**: Mobile-first approach with optimized layouts for all devices
- **Accessibility**: ARIA labels, keyboard navigation, and proper contrast ratios

feat: Redesign Smart Crop Recommender with modern UI and enhanced UX

---

index.html
style.css

Which issue does this PR close?
Closes #322 
Rationale for this change:
The current footer of the AgriTech website appears misaligned and cluttered. The "Quick Links," "Smart Tools," and mission statement are not properly justified, which affects both usability and the professional appearance of the site. The mission statement, in particular, looks untidy due to poor text alignment. Improving the footer layout and mission statement display will enhance readability, user experience, and overall brand perception.
What changes are included in this PR?
- Restructured the footer using flexbox/grid layout for better alignment of "Quick Links," "Smart Tools," and the mission statement.
- Adjusted the mission statement "Empowering India's Farming Future with innovative technology solutions that …

Enhance Footer Layout and Mission Statement Display

---

faq.html
index.html
style.css

Which issue does this PR close?
Closes #321 
Rationale for this change:
The AgriTech website currently lacks a dedicated FAQ section, making it difficult for users—including farmers, buyers, suppliers, and sellers—to find quick answers to common questions. This leads to user confusion and unnecessary support requests. By adding a dedicated FAQ section, we provide self-service support, reduce support load, and improve trust and transparency on the platform.
What changes are included in this PR?
- Added an FAQ link in the header navigation bar (placed next to Login and Register).
- Created a new faq.html page with a clean, accordion-style Q&A layout matching AgriTech’s branding and dark theme.
- Added initial set of FAQ questions, such as:
1. What is AgriTech and how does it work?
2. How do …

Add FAQ Section to header(open dedicated page)

---

blog.css
blog.html
blog.js
index.html

- Closes #310  
Adds a blog section to provide farming tips, technology insights, market trends, and sustainability updates.  
Helps users stay informed and improves platform engagement.  
- Implemented blog section UI (`AgriTech Blog`)  
- Added category filters (Farming Tips, Technology, Market Trends, Sustainability, Business)  
- Added search functionality for blog posts  
- Designed responsive blog card layout with images and metadata  
- Frontend-only implementation  
- Ready for integration with backend blog API

✨ Feature: Add Blog Section for Farming Tips & Updates (#310)

---

chat.html

- Closes #319 
The Back to Home button in chat.html was not redirecting users to the main homepage. Updating the href ensures users are properly navigated when clicking the button.
Corrected the previous incorrect path to point to the actual homepage (index.html).
Tested manually by opening chat.html and clicking the Back to Home button to confirm proper redirection.
Yes, users clicking the Back to Home button will now be redirected to the index page as intended.

Fix Back to Home Button Redirect in chat.html

---

chat.css
chat.html
chat.js
chatbot-responses.json
json-chatbot.js

- Closes #347
The current chatbox is not responsive and does not provide meaningful replies, reducing user engagement.  
By adding a **bot trained with JSON data**, the chatbox becomes interactive, helpful, and user-friendly.
- Implemented a **responsive chatbot** that reads responses from a JSON training file.  
- Added support for multiple fields in JSON:  
- `query`: user’s input  
- `response`: bot reply  
- Fallback response when no match is found.  
- Integrated chatbot into the existing **chatbox UI**.  
- Fixed duplicated text issue and improved **dark/light mode compatibility**.  
- Added smooth animations and responsive layout for mobile + desktop.  
```json
[
{
"query": "hello",
"response": "Hi there! 👋 How can I help you today?"
},
{
"query": "how are you",
"response": "I'm …
```

feat: Implement JSON chatbot with smart matching and mobile optimization

---

Crop Yield Prediction/crop_yield_app/templates/index.html

- Closes #348 
---
The Jinja template code (`{% for key, value in params.items() %}...{% endfor %}`) needed to pass parameters for the PDF download was being displayed directly on the front-end of the crop recommendation result page, confusing users and breaking the design. 
This change corrects the HTML structure to ensure the Jinja code is correctly nested within the `<form>` element as hidden inputs, resolving the visual bug while maintaining the required form functionality. It also refines the button CSS for better responsiveness and alignment.
---
1.  **Structural HTML Fix:** The Jinja loop and the hidden `<input type="hidden">` fields for passing parameters (`params` and `crop`) are now correctly placed **inside** the `<form method="post" action="/download_report">`. This prevents …

Redesigned the yield prediction page 

---

crop.html
financial-support.html
index.html
marketplace.html
supply-chain.html
sustainable-farming.html

Closes #351
This PR adds a structured and interactive Service Section to the project, making it easier for users to view, explore, and toggle different agricultural services. It improves the website’s usability and presentation
- Added a Service Section with multiple services displayed.
- Implemented toggle/expand features for each service to show details.
- Styled section using HTML, CSS, and JavaScript for better UI/UX.
- Ensured responsiveness for different screen sizes.
✅ Manually tested in local environment.
✅ Verified toggle functionality works correctly.
✅ Checked responsiveness on multiple screen sizes.
- Yes. A new Service Section is now visible on the website.
- Users can interact with toggles to view service details.

Fixes #351: Added Services Section

---

Community/app.py
Crop_Planning/app.py
Forum/app.py
auth_utils.py

…Forum, and Crop_Planning modules (#382)
- Closes #382 .
@omroy07

Implement Authentication and Role-Based Access Control Across All Modules (#382)

---

.github/workflows/python-app.yml
Crop Recommendation/app.py
Crop Yield Prediction/crop_yield_app/app.py
tests/test_crop_planning.py

Added a basic backend test and set up GitHub Actions to automatically run tests on every pull request. This helps catch bugs early and keeps the code reliable.#397
- Closes #397
@omroy07

Add automated backend testing and continuous integration (CI) workflow
